# Generated by Django 2.0.3 on 2018-12-16 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20181201_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creater',
            name='thumnail',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
