# Generated by Django 2.0.3 on 2018-12-31 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_review_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(0, '未視聴'), (1, '後で見る'), (2, '視聴済み')], max_length=1)),
                ('title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.Item')),
                ('watch_from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_from_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='follow',
            name='from_user',
        ),
        migrations.RemoveField(
            model_name='score',
            name='score_user',
        ),
        migrations.AddField(
            model_name='follow',
            name='follow_from_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follow_from_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='review_from_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_from_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='score',
            name='score_from_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='score_from_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
