# Generated by Django 2.0.3 on 2018-12-31 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20181231_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='follow',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='follow_from_user',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='follower',
        ),
        migrations.RemoveField(
            model_name='review',
            name='review_from_user',
        ),
        migrations.RemoveField(
            model_name='review',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='review',
            name='title',
        ),
        migrations.RemoveField(
            model_name='score',
            name='score_from_user',
        ),
        migrations.RemoveField(
            model_name='score',
            name='title',
        ),
        migrations.RemoveField(
            model_name='watchstatus',
            name='title',
        ),
        migrations.RemoveField(
            model_name='watchstatus',
            name='watch_from_user',
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='Score',
        ),
        migrations.DeleteModel(
            name='WatchStatus',
        ),
    ]
