# Generated by Django 2.0.3 on 2019-01-01 23:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_follow_review_score_watchstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='disliked',
            field=models.ManyToManyField(blank=True, related_name='review_disliked_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='liked',
            field=models.ManyToManyField(blank=True, related_name='review_liked_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='score',
            name='score',
            field=models.IntegerField(choices=[(0, '未評価'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], max_length=2),
        ),
        migrations.AlterField(
            model_name='watchstatus',
            name='status',
            field=models.IntegerField(choices=[(0, '未視聴'), (1, '後で見る'), (2, '視聴済み')], max_length=1),
        ),
    ]
