# Generated by Django 2.0.3 on 2019-01-03 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_auto_20190101_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchstatus',
            name='stock',
            field=models.IntegerField(choices=[(1, '後で見るへ追加'), (2, '後で見る解除')], null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='score',
            field=models.IntegerField(choices=[(0, '未評価'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')]),
        ),
        migrations.AlterField(
            model_name='watchstatus',
            name='status',
            field=models.IntegerField(choices=[(1, '未視聴'), (2, '視聴済み')], null=True),
        ),
    ]
