# Generated by Django 2.0.3 on 2019-01-03 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_auto_20190103_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchstatus',
            name='status',
            field=models.IntegerField(choices=[(1, '未視聴'), (2, '視聴済み')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='watchstatus',
            name='stock',
            field=models.IntegerField(choices=[(1, '後で見るへ追加'), (2, '後で見る解除')], default=1, null=True),
        ),
    ]
