# Generated by Django 2.0.3 on 2019-01-03 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_auto_20190103_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchstatus',
            name='stock',
        ),
        migrations.AlterField(
            model_name='watchstatus',
            name='status',
            field=models.IntegerField(choices=[(1, '未視聴'), (2, '視聴済み')], null=True),
        ),
    ]
