# Generated by Django 2.0.3 on 2019-01-04 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_auto_20190103_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchstatus',
            name='stock',
            field=models.IntegerField(choices=[(0, '後で見るへ'), (2, '後で見る 解除')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='watchstatus',
            name='status',
            field=models.IntegerField(choices=[(0, '未視聴'), (2, '視聴済み')], max_length=1, null=True),
        ),
    ]
