# Generated by Django 2.0.3 on 2019-01-05 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_auto_20190105_2148'),
    ]

    operations = [
    ]
