# Generated by Django 2.0.3 on 2019-01-06 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_auto_20190105_2358'),
    ]

    operations = [
    ]
